### ISSUE TITLE
Music List

### ISSUE THREAD

**Issue by wildskyf** [wi1d5ky/WebGL-DNA#5]
Now we have 2 songs:
- SoDaGreen - No sleep [Taiwanese]
- Fish [Japanese]

We need 3 more. What do you like? @hane1818

**Comment by hane1818** [comment]
How about:
- Bruno Mars - Just The Way You Are
- Bruno Mars - Count On Me
- Taylor Swift - We Are Never Ever Getting Back Together 
- Taylor Swift - Shake It Off
- Tommy heavenly6 - Hey My Friend [Japanese]
- Davichi & T-ara - We were in love [Korean]
- Yoon Mi Rae - I'll Listen to What You Have to Say [Korean]
- Sako Tomohisa - Bye bye [Japanese]
- Angela Zhang - Visible Wings [Chinese]
- YUI - fight [Japanese]
- Remioromen - Konayuki [Japanese]
- Remioromen - Sangatsu Kokonoka [Japanese]

You can listen and choose what u want.

**Comment by wildskyf** [comment]
Here are our list of songs:
- 蘇打綠 - 無眠 [Taiwanese]
- Fish [Japanese]
- Bruno Mars - Just The Way You Are [English]
- Yoon Mi Rae - I'll Listen to What You Have to Say [Korean]
- Beyond - 海闊天空 [Cantonese]

**Comment by hane1818** [comment]
Done.
